(dp1
S'output'
p2
S"<class 'novaclient.exceptions.ClientException'> Unknown Error (HTTP 503)"
p3
sS'layer'
p4
S'/home/archer/Documents/web2py/applications/baadal/controllers/action.py'
p5
sS'code'
p6
S'import Baadal\nimport json\ndef start():\n    conn = Baadal.Connection("http://10.237.23.178:35357/v2.0", "admin", "admin", "baadal")\n    if conn:\n        vmid = request.vars.vmid\n        vm = conn.findBaadalVM(id=\'e3192a6d-200f-45c0-b5e5-2f9d2008be20\')\n        if vm:\n            #vm.start()\n            pass\n        return json.dumps(dict(status=\'success\'))\n    else:\n        return json.dumps(dict(status=\'failure\'))\n\n\nresponse._vars=response._caller(start)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/archer/Documents/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/archer/Documents/web2py/applications/baadal/controllers/action.py", line 16, in <module>\n  File "/home/archer/Documents/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/archer/Documents/web2py/applications/baadal/controllers/action.py", line 7, in start\n    vm = conn.findBaadalVM(id=\'e3192a6d-200f-45c0-b5e5-2f9d2008be20\')\n  File "applications/baadal/modules/Baadal.py", line 372, in findBaadalVM\n    baadalVM = self.__conn[\'nova\'].servers.find(**kwargs)\n  File "/home/archer/Documents/python-openstack/local/lib/python2.7/site-packages/novaclient/base.py", line 196, in find\n    matches = self.findall(**kwargs)\n  File "/home/archer/Documents/python-openstack/local/lib/python2.7/site-packages/novaclient/base.py", line 249, in findall\n    listing = self.list(**list_kwargs)\n  File "/home/archer/Documents/python-openstack/local/lib/python2.7/site-packages/novaclient/v2/servers.py", line 600, in list\n    return self._list("/servers%s%s" % (detail, query_string), "servers")\n  File "/home/archer/Documents/python-openstack/local/lib/python2.7/site-packages/novaclient/base.py", line 64, in _list\n    _resp, body = self.api.client.get(url)\n  File "/home/archer/Documents/python-openstack/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 170, in get\n    return self.request(url, \'GET\', **kwargs)\n  File "/home/archer/Documents/python-openstack/local/lib/python2.7/site-packages/novaclient/client.py", line 103, in request\n    raise exceptions.from_response(resp, body, url, method)\nClientException: Unknown Error (HTTP 503)\n'
p11
s.